name: chess_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.1.0
  flutter_chess_board: ^1.0.1
  chess: ^0.7.0
  stockfish: ^1.7.1
  http: ^1.6.0
  confetti: ^0.7.0
  firebase_database: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/chess_bg.jpg
    - assets/images/google_logo.jpg
    - assets/images/main_logo.jpg
    - assets/images/home_bg.jpg